language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update --quiet
  - sudo apt-get install --yes build-essential
  - sudo apt-get install --yes

script:
  - clang --version
  - gcc --version
