import os

Import('env')

# copy parent environment so our alterations don't affect it
env = env.Clone()

print "env['CPPPATH']:", env['CPPPATH']

# print ""
# # add source directories (at all levels) to the include path
# # and add their contents are build targets
# matches = []
# for root, dirnames, filenames in os.walk(os.getcwd()):
# 	print "###", os.getcwd(), filenames
# 	for dirname in dirnames:
# 		print('adding dir to path: %s' % dirname)
# 		env.Append(CPPPATH=[dirname])
# 		globStr = "%s/*.c*" % dirname
# 		matches.append(Glob(globStr))

# # debug output
# print src env CPPPATH:
# print env['CPPPATH']

# Library('libmathy', ['mathy.cc'])
# print ""
# # build a shared library
# env.SharedLibrary('../../out/bin/libmathy', matches)
